FROM eclipse-temurin:17-jre
WORKDIR /app

ENV SERVER_PORT=9999
ENV FILE_UPLOAD_PATH=/app/uploads

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /app/app.jar

EXPOSE 9999

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
